Adding some needs in tests, the first to be done is the compiling. Adding the valgrind errors check, now checking if there is any valgrind errors, this DON'T check the leaks, only memory errors

diff --git a/.github/workflows/epitech-actions.yml b/.github/workflows/epitech-actions.yml
--- a/.github/workflows/epitech-actions.yml
+++ b/.github/workflows/epitech-actions.yml
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  can_compile:
+  Compiling:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -21,9 +21,9 @@ jobs:
         run: |
           make
 
-  style_check:
+  Coding-Style:
     runs-on: ubuntu-latest
-    needs: can_compile
+    needs: Compiling
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -50,10 +50,42 @@ jobs:
         with:
           name: style-check-report
           path: epitech-actions-output-style.txt
-
-  test:
+  
+  Valgrind-Errors:
     runs-on: ubuntu-latest
-    needs: style_check
+    needs: Compiling
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install dependencies
+        run: |
+          sudo apt update
+          sudo apt install -y make gcc valgrind
+
+      - name: Extract binary name
+        run: echo "BINARY_NAME=$(grep '^NAME[[:space:]]*=' Makefile | sed 's/NAME[[:space:]]*=[[:space:]]*//')" >> $GITHUB_ENV
+
+      - name: Run Valgrind
+        run: |
+          make
+          if [ -f "${{ env.BINARY_NAME }}" ]; then
+            valgrind --leak-check=full ./${{ env.BINARY_NAME }} 2>&1 | tee valgrind_output.txt
+            if grep -q "ERROR SUMMARY: 0 errors from 0 contexts" valgrind_output.txt; then
+            echo "::notice::No memory leaks detected."
+              exit 0
+            else
+              echo "::error::Memory leaks detected or another issue occurred."
+              exit 1
+            fi
+          else
+            echo "Error: Binary '${{ env.BINARY_NAME }}' not found!"
+            exit 1
+          fi
+
+  Unit-Tests-Criterion:
+    runs-on: ubuntu-latest
+    needs: Compiling
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
