[~] Did some change concerning the checking of undefined symbols, and removed tests files

diff --git a/.github/workflows/epitech-actions.yml b/.github/workflows/epitech-actions.yml
--- a/.github/workflows/epitech-actions.yml
+++ b/.github/workflows/epitech-actions.yml
@@ -5,6 +5,9 @@ on:
     branches:
       - main
 
+env:
+  ALLOWED_PATH: .github/workflows/allowed_functions.txt
+
 jobs:
   Compiling:
     runs-on: ubuntu-latest
@@ -29,21 +32,31 @@ jobs:
 
       - name: Build project
         run: make
-      
+
       - name: Extract binary name
-        run: echo "BINARY_NAME=$(grep '^NAME[[:space:]]*=' Makefile | sed 's/NAME[[:space:]]*=[[:space:]]*//')" >> $GITHUB_ENV
+        run: |
+          echo "BINARY_NAME=$(grep '^NAME[[:space:]]*=' Makefile | sed 's/NAME[[:space:]]*=[[:space:]]*//')" >> $GITHUB_ENV
+
+      - name: Show files (debug)
+        run: ls -la .github/workflows/
 
       - name: Check allowed symbols
         run: |
           echo "Checking undefined symbols in binary..."
-          symbols=$(nm -u $BINARY_NAME | sed '/U _/d'| grep ' U ' | grep '@' | cut -d'@' -f1 | sort -u)
+
+          if [ ! -f "$ALLOWED_PATH" ]; then
+            echo "Error: $ALLOWED_PATH not found!"
+            exit 1
+          fi
+
+          symbols=$(nm -u ${{ env.BINARY_NAME }} | sed '/U _/d' | grep ' U ' | grep '@' | cut -d'@' -f1 | sort -u)
 
           echo "Found symbols:"
           echo "$symbols"
 
           unauthorized=()
           while read -r sym; do
-            if ! grep -qx "$sym" ./allowed_functions.txt; then
+            if ! grep -qx "$sym" "$ALLOWED_PATH"; then
               unauthorized+=("$sym")
             fi
           done <<< "$symbols"
@@ -77,7 +90,7 @@ jobs:
             done < coding-style-reports.log
             exit 1
           fi
-  
+
   Valgrind-Errors:
     runs-on: ubuntu-latest
     needs: Compiling
@@ -99,7 +112,7 @@ jobs:
           if [ -f "${{ env.BINARY_NAME }}" ]; then
             valgrind --leak-check=full ./${{ env.BINARY_NAME }} 2>&1 | tee valgrind_output.txt
             if grep -q "ERROR SUMMARY: 0 errors from 0 contexts" valgrind_output.txt; then
-            echo "::notice::No memory leaks detected."
+              echo "::notice::No memory leaks detected."
               exit 0
             else
               echo "::error::Memory leaks detected or another issue occurred."
